const APP_NETWORKS_SETTING = 'APP_NETWORKS_SETTING';
const APP_NETWORKS_SETTING_SUCCESS = 'APP_NETWORKS_SETTING_SUCCESS';
const APP_NETWORKS_SETTING_ERROR = 'APP_NETWORKS_SETTING_ERROR';
const APP_NETWORKS_SETTING_CLEAR = 'APP_NETWORKS_SETTING_CLEAR';

const SELECT_NETWORK = 'SELECT_NETWORK';
const UPDATE_WALLET_NETWORK = 'UPDATE_WALLET_NETWORK';
const CHANGE_NETWORK = 'CHANGE_NETWORK';
const CHANGE_NETWORK_SUCCESS = 'CHANGE_NETWORK_SUCCESS';
const CHANGE_NETWORK_FAILED = 'CHANGE_NETWORK_FAILED';


const CONNECTOR_SETTING_LOADING = 'CONNECTOR_SETTING_LOADING';
const CONNECTOR_SETTING_SUCCESS = 'CONNECTOR_SETTING_SUCCESS';
const CONNECTOR_SETTING_ERROR = 'CONNECTOR_SETTING_ERROR';
const CONNECTOR_SETTING_CLEAR = 'CONNECTOR_SETTING_CLEAR';

export const appNetworkActions = {
  APP_NETWORKS_SETTING,
  APP_NETWORKS_SETTING_SUCCESS,
  APP_NETWORKS_SETTING_ERROR,
  APP_NETWORKS_SETTING_CLEAR,
  CONNECTOR_SETTING_LOADING,
  CONNECTOR_SETTING_SUCCESS,
  CONNECTOR_SETTING_CLEAR,
  CONNECTOR_SETTING_ERROR,
  SELECT_NETWORK,
  UPDATE_WALLET_NETWORK,
  CHANGE_NETWORK,
  CHANGE_NETWORK_SUCCESS,
  CHANGE_NETWORK_FAILED,
}
