version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: antedao-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: antedaoproduction
      MYSQL_USER: 'antedao'
      MYSQL_PASSWORD: 'antedao2303production'
      LANG: C.UTF-8
    ports:
      - 6668:3306
    volumes:
      - .data/mysql:/var/lib/mysql

  redis:
    image: 'redis:6-alpine'
    container_name: antedao-redis
    ports:
      - 6669:6379
    volumes:
      - .data/redis:/data
