
const SETTING_STAKING_POOL_LOADING = 'SETTING_STAKING-POOL_LOADING';
const SETTING_STAKING_POOL_SUCCESS = 'SETTING_STAKING-POOL_SUCCESS';
const SETTING_STAKING_POOL_FAILURE = 'SETTING_STAKING-POOL_FAILURE';

export const settingStakingPoolActions = {
  SETTING_STAKING_POOL_LOADING,
  SETTING_STAKING_POOL_SUCCESS,
  SETTING_STAKING_POOL_FAILURE,
};
